backend/web/config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :package_file_attachments
  resources :workflow_step_packages
  resources :workflow_packages
  resources :file_types
  resources :categories
  resources :file_attachments do
    collection do
      post 'create/multiple', to: 'file_attachments#create_multiple'
    end
  end
  resources :knowledge_articles
  resources :workflow_steps
  resources :workflows
  resources :workflow_types
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount_devise_token_auth_for 'User', at: 'auth'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
end

backend/web/app/models/workflow_package.rb
class WorkflowPackage < ApplicationRecord
  belongs_to :workflow
  belongs_to :user
  has_many :workflow_step_packages

  validates :workflow, :user, presence: true
end

backend/web/app/controllers/workflow_packages_controller.rb
class WorkflowPackagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workflow_package, only: [:show, :edit, :update, :destroy]

  # GET /workflow_packages
  # GET /workflow_packages.json
  def index
    @workflow_packages = current_user.workflow_packages.where(workflow_id: params[:workflow_id])
  end

  # GET /workflow_packages/1
  # GET /workflow_packages/1.json
  def show
  end

  # GET /workflow_packages/new
  def new
    @workflow_package = WorkflowPackage.new
  end

  # GET /workflow_packages/1/edit
  def edit
  end

  # POST /workflow_packages
  # POST /workflow_packages.json
  def create
    @workflow_package = WorkflowPackage.new(workflow_package_params)

    respond_to do |format|
      if @workflow_package.save
        format.html { redirect_to @workflow_package, notice: 'Workflow package was successfully created.' }
        format.json { render :show, status: :created, location: @workflow_package }
      else
        format.html { render :new }
        format.json { render json: @workflow_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflow_packages/1
  # PATCH/PUT /workflow_packages/1.json
  def update
    respond_to do |format|
      if @workflow_package.user == current_user && @workflow_package.update(workflow_package_params)
        format.html { redirect_to @workflow_package, notice: 'Workflow package was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow_package }
      else
        format.html { render :edit }
        format.json { render json: @workflow_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflow_packages/1
  # DELETE /workflow_packages/1.json
  def destroy
    @workflow_package.destroy if @workflow_package.user == current_user
    respond_to do |format|
      format.html { redirect_to workflow_packages_url, notice: 'Workflow package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow_package
      @workflow_package = WorkflowPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_package_params
      params.require(:workflow_package).permit(:workflow_id, :name, :description, :user_id)
    end
end

backend/web/app/helpers/workflow_packages_helper.rb
module WorkflowPackagesHelper
end

backend/web/app/views/workflow_packages/_form.html.erb
<%= form_for(workflow_package) do |f| %>
  <% if workflow_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workflow_package.errors.count, "error") %> prohibited this workflow_package from being saved:</h2>

      <ul>
      <% workflow_package.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workflow_id %>
    <%= f.text_field :workflow_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/web/app/views/workflow_packages/edit.html.erb
<h1>Editing Workflow Package</h1>

<%= render 'form', workflow_package: @workflow_package %>

<%= link_to 'Show', @workflow_package %> |
<%= link_to 'Back', workflow_packages_path %>

backend/web/app/views/workflow_packages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workflow Packages</h1>

<table>
  <thead>
    <tr>
      <th>Workflow</th>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflow_packages.each do |workflow_package| %>
      <tr>
        <td><%= workflow_package.workflow %></td>
        <td><%= workflow_package.name %></td>
        <td><%= workflow_package.description %></td>
        <td><%= workflow_package.user %></td>
        <td><%= link_to 'Show', workflow_package %></td>
        <td><%= link_to 'Edit', edit_workflow_package_path(workflow_package) %></td>
        <td><%= link_to 'Destroy', workflow_package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow Package', new_workflow_package_path %>

backend/web/app/views/workflow_packages/new.html.erb
<h1>New Workflow Package</h1>

<%= render 'form', workflow_package: @workflow_package %>

<%= link_to 'Back', workflow_packages_path %>

backend/web/app/views/workflow_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workflow:</strong>
  <%= @workflow_package.workflow %>
</p>

<p>
  <strong>Name:</strong>
  <%= @workflow_package.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workflow_package.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @workflow_package.user %>
</p>

<%= link_to 'Edit', edit_workflow_package_path(@workflow_package) %> |
<%= link_to 'Back', workflow_packages_path %>