backend/web/config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :package_file_attachments
  resources :workflow_step_packages
  resources :workflow_packages
  resources :file_types
  resources :categories
  resources :file_attachments do
    collection do
      post 'create/multiple', to: 'file_attachments#create_multiple'
    end
  end
  resources :knowledge_articles
  resources :workflow_steps
  resources :workflows
  resources :workflow_types
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount_devise_token_auth_for 'User', at: 'auth'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
end

backend/web/app/models/workflow_step.rb
class WorkflowStep < ApplicationRecord
  belongs_to :workflow
  has_many :workflow_step_knowledge_articles
  has_many :knowledge_articles, through: :workflow_step_knowledge_articles

  validates :name, :workflow_id, presence: true

  default_scope {order(id: :asc)}
end

backend/web/app/controllers/workflow_steps_controller.rb
class WorkflowStepsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource # for cancancan

  before_action :set_workflow_step, only: [:show, :edit, :update, :destroy]
  before_action :current_user_is_admin?, only: [:create, :update, :destroy]

  # GET /workflow_steps
  # GET /workflow_steps.json
  def index
    @workflow_steps = WorkflowStep.all
  end

  # GET /workflow_steps/1
  # GET /workflow_steps/1.json
  def show
  end

  # GET /workflow_steps/new
  def new
    @workflow_step = WorkflowStep.new
  end

  # GET /workflow_steps/1/edit
  def edit
  end

  # POST /workflow_steps
  # POST /workflow_steps.json
  def create
    @workflow_step = WorkflowStep.new(workflow_step_params)

    respond_to do |format|
      if @workflow_step.save
        format.html { redirect_to @workflow_step, notice: 'Workflow step was successfully created.' }
        format.json { render :show, status: :created, location: @workflow_step }
      else
        format.html { render :new }
        format.json { render json: @workflow_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflow_steps/1
  # PATCH/PUT /workflow_steps/1.json
  def update
    respond_to do |format|
      if @workflow_step.update(workflow_step_params)
        format.html { redirect_to @workflow_step, notice: 'Workflow step was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow_step }
      else
        format.html { render :edit }
        format.json { render json: @workflow_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflow_steps/1
  # DELETE /workflow_steps/1.json
  def destroy
    @workflow_step.destroy
    respond_to do |format|
      format.html { redirect_to workflow_steps_url, notice: 'Workflow step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow_step
      @workflow_step = WorkflowStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_step_params
      params.require(:workflow_step).permit(:workflow_id, :name, :description, :string)
    end
end

backend/web/app/helpers/workflow_steps_helper.rb
module WorkflowStepsHelper
end

backend/web/app/views/workflow_steps/_form.html.erb
<%= form_for(workflow_step) do |f| %>
  <% if workflow_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workflow_step.errors.count, "error") %> prohibited this workflow_step from being saved:</h2>

      <ul>
      <% workflow_step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workflow_id %>
    <%= f.text_field :workflow_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/web/app/views/workflow_steps/edit.html.erb
<h1>Editing Workflow Step</h1>

<%= render 'form', workflow_step: @workflow_step %>

<%= link_to 'Show', @workflow_step %> |
<%= link_to 'Back', workflow_steps_path %>

backend/web/app/views/workflow_steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workflow Steps</h1>

<table>
  <thead>
    <tr>
      <th>Workflow</th>
      <th>Name</th>
      <th>Description</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflow_steps.each do |workflow_step| %>
      <tr>
        <td><%= workflow_step.workflow %></td>
        <td><%= workflow_step.name %></td>
        <td><%= workflow_step.description %></td>
        <td><%= workflow_step.string %></td>
        <td><%= link_to 'Show', workflow_step %></td>
        <td><%= link_to 'Edit', edit_workflow_step_path(workflow_step) %></td>
        <td><%= link_to 'Destroy', workflow_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow Step', new_workflow_step_path %>

backend/web/app/views/workflow_steps/new.html.erb
<h1>New Workflow Step</h1>

<%= render 'form', workflow_step: @workflow_step %>

<%= link_to 'Back', workflow_steps_path %>

backend/web/app/views/workflow_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workflow:</strong>
  <%= @workflow_step.workflow %>
</p>

<p>
  <strong>Name:</strong>
  <%= @workflow_step.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workflow_step.description %>
</p>

<p>
  <strong>String:</strong>
  <%= @workflow_step.string %>
</p>

<%= link_to 'Edit', edit_workflow_step_path(@workflow_step) %> |
<%= link_to 'Back', workflow_steps_path %>