backend/web/config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :package_file_attachments
  resources :workflow_step_packages
  resources :workflow_packages
  resources :file_types
  resources :categories
  resources :file_attachments do
    collection do
      post 'create/multiple', to: 'file_attachments#create_multiple'
    end
  end
  resources :knowledge_articles
  resources :workflow_steps
  resources :workflows
  resources :workflow_types
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount_devise_token_auth_for 'User', at: 'auth'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
end

backend/web/app/controllers/workflow_types_controller.rb
class WorkflowTypesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource # for cancancan
  
  before_action :set_workflow_type, only: [:show, :edit, :update, :destroy]
  before_action :current_user_is_admin?, only: [:create, :update, :destroy]

  # GET /workflow_types
  # GET /workflow_types.json
  def index
    @workflow_types = WorkflowType.all
  end

  # GET /workflow_types/1
  # GET /workflow_types/1.json
  def show
  end

  # GET /workflow_types/new
  def new
    @workflow_type = WorkflowType.new
  end

  # GET /workflow_types/1/edit
  def edit
  end

  # POST /workflow_types
  # POST /workflow_types.json
  def create
    @workflow_type = WorkflowType.new(workflow_type_params)

    respond_to do |format|
      if @workflow_type.save
        format.html { redirect_to @workflow_type, notice: 'Workflow type was successfully created.' }
        format.json { render :show, status: :created, location: @workflow_type }
      else
        format.html { render :new }
        format.json { render json: @workflow_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflow_types/1
  # PATCH/PUT /workflow_types/1.json
  def update
    respond_to do |format|
      if @workflow_type.update(workflow_type_params)
        format.html { redirect_to @workflow_type, notice: 'Workflow type was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow_type }
      else
        format.html { render :edit }
        format.json { render json: @workflow_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflow_types/1
  # DELETE /workflow_types/1.json
  def destroy
    @workflow_type.destroy
    respond_to do |format|
      format.html { redirect_to workflow_types_url, notice: 'Workflow type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow_type
      @workflow_type = WorkflowType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_type_params
      params.require(:workflow_type).permit(:name, :description)
    end
end

backend/web/app/helpers/workflow_types_helper.rb
module WorkflowTypesHelper
end

backend/web/app/views/workflow_types/_form.html.erb
<%= form_for(workflow_type) do |f| %>
  <% if workflow_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workflow_type.errors.count, "error") %> prohibited this workflow_type from being saved:</h2>

      <ul>
      <% workflow_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/web/app/views/workflow_types/edit.html.erb
<h1>Editing Workflow Type</h1>

<%= render 'form', workflow_type: @workflow_type %>

<%= link_to 'Show', @workflow_type %> |
<%= link_to 'Back', workflow_types_path %>

backend/web/app/views/workflow_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workflow Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflow_types.each do |workflow_type| %>
      <tr>
        <td><%= workflow_type.name %></td>
        <td><%= workflow_type.description %></td>
        <td><%= link_to 'Show', workflow_type %></td>
        <td><%= link_to 'Edit', edit_workflow_type_path(workflow_type) %></td>
        <td><%= link_to 'Destroy', workflow_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow Type', new_workflow_type_path %>

backend/web/app/views/workflow_types/new.html.erb
<h1>New Workflow Type</h1>

<%= render 'form', workflow_type: @workflow_type %>

<%= link_to 'Back', workflow_types_path %>

backend/web/app/views/workflow_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @workflow_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @workflow_type.description %>
</p>

<%= link_to 'Edit', edit_workflow_type_path(@workflow_type) %> |
<%= link_to 'Back', workflow_types_path %>