backend/web/config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :package_file_attachments
  resources :workflow_step_packages
  resources :workflow_packages
  resources :file_types
  resources :categories
  resources :file_attachments do
    collection do
      post 'create/multiple', to: 'file_attachments#create_multiple'
    end
  end
  resources :knowledge_articles
  resources :workflow_steps
  resources :workflows
  resources :workflow_types
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  mount_devise_token_auth_for 'User', at: 'auth'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
end

backend/web/app/models/workflow_step_package.rb
class WorkflowStepPackage < ApplicationRecord
  belongs_to :workflow_package
  belongs_to :workflow_step
  belongs_to :user
  has_many :package_file_attachments

  validates :user, :workflow_package, :workflow_step, presence: true
end

backend/web/app/controllers/workflow_step_packages_controller.rb
class WorkflowStepPackagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_workflow_step_package, only: [:show, :edit, :update, :destroy]

  # GET /workflow_step_packages
  # GET /workflow_step_packages.json
  def index
    @workflow_step_packages = current_user.workflow_step_packages.where(workflow_package_id: params[:workflow_package_id])
  end

  # GET /workflow_step_packages/1
  # GET /workflow_step_packages/1.json
  def show
  end

  # GET /workflow_step_packages/new
  def new
    @workflow_step_package = WorkflowStepPackage.new
  end

  # GET /workflow_step_packages/1/edit
  def edit
  end

  # POST /workflow_step_packages
  # POST /workflow_step_packages.json
  def create
    @workflow_step_package = WorkflowStepPackage.new(workflow_step_package_params)

    respond_to do |format|
      if @workflow_step_package.save
        format.html { redirect_to @workflow_step_package, notice: 'Workflow step package was successfully created.' }
        format.json { render :show, status: :created, location: @workflow_step_package }
      else
        format.html { render :new }
        format.json { render json: @workflow_step_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflow_step_packages/1
  # PATCH/PUT /workflow_step_packages/1.json
  def update
    respond_to do |format|
      if @workflow_step_package.user == current_user && @workflow_step_package.update(workflow_step_package_params)
        format.html { redirect_to @workflow_step_package, notice: 'Workflow step package was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow_step_package }
      else
        format.html { render :edit }
        format.json { render json: @workflow_step_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workflow_step_packages/1
  # DELETE /workflow_step_packages/1.json
  def destroy
    @workflow_step_package.destroy if @workflow_step_package.user == current_user
    respond_to do |format|
      format.html { redirect_to workflow_step_packages_url, notice: 'Workflow step package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow_step_package
      @workflow_step_package = WorkflowStepPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workflow_step_package_params
      params.require(:workflow_step_package).permit(:workflow_package_id, :workflow_step_id, :user_id)
    end
end

backend/web/app/helpers/workflow_step_packages_helper.rb
module WorkflowStepPackagesHelper
end

backend/web/app/views/workflow_step_packages/_form.html.erb
<%= form_for(workflow_step_package) do |f| %>
  <% if workflow_step_package.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workflow_step_package.errors.count, "error") %> prohibited this workflow_step_package from being saved:</h2>

      <ul>
      <% workflow_step_package.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :workflow_package_id %>
    <%= f.text_field :workflow_package_id %>
  </div>

  <div class="field">
    <%= f.label :workflow_step_id %>
    <%= f.text_field :workflow_step_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

backend/web/app/views/workflow_step_packages/edit.html.erb
<h1>Editing Workflow Step Package</h1>

<%= render 'form', workflow_step_package: @workflow_step_package %>

<%= link_to 'Show', @workflow_step_package %> |
<%= link_to 'Back', workflow_step_packages_path %>

backend/web/app/views/workflow_step_packages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workflow Step Packages</h1>

<table>
  <thead>
    <tr>
      <th>Workflow package</th>
      <th>Workflow step</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workflow_step_packages.each do |workflow_step_package| %>
      <tr>
        <td><%= workflow_step_package.workflow_package %></td>
        <td><%= workflow_step_package.workflow_step %></td>
        <td><%= workflow_step_package.user %></td>
        <td><%= link_to 'Show', workflow_step_package %></td>
        <td><%= link_to 'Edit', edit_workflow_step_package_path(workflow_step_package) %></td>
        <td><%= link_to 'Destroy', workflow_step_package, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Workflow Step Package', new_workflow_step_package_path %>

backend/web/app/views/workflow_step_packages/new.html.erb
<h1>New Workflow Step Package</h1>

<%= render 'form', workflow_step_package: @workflow_step_package %>

<%= link_to 'Back', workflow_step_packages_path %>

backend/web/app/views/workflow_step_packages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Workflow package:</strong>
  <%= @workflow_step_package.workflow_package %>
</p>

<p>
  <strong>Workflow step:</strong>
  <%= @workflow_step_package.workflow_step %>
</p>

<p>
  <strong>User:</strong>
  <%= @workflow_step_package.user %>
</p>

<%= link_to 'Edit', edit_workflow_step_package_path(@workflow_step_package) %> |
<%= link_to 'Back', workflow_step_packages_path %>